#!/usr/bin/env node
/**
 * Runs Orbit's question bank against the running app, on a loop, and writes
 * the trend to docs/selfeval.md.
 *
 *   node scripts/selfeval-loop.mjs               # every 10 minutes
 *   node scripts/selfeval-loop.mjs --once        # one run, then exit
 *   node scripts/selfeval-loop.mjs --every 120   # seconds
 *
 * What this is, precisely: **no weights change.** Nothing here trains a
 * model. It asks Orbit the same questions repeatedly against whatever state
 * the app is really in -- a different time of day, an imported calendar, a
 * cancelled class -- and records whether the answers stayed grounded, stayed
 * on target and stayed honest about what it does not know.
 *
 * That matters more than a one-off score. The bank passed at 100% on a
 * Saturday evening with no class left to catch; the interesting question is
 * whether it still does at 9am on a Tuesday with a live bus and a deadline,
 * and this is what answers it without anyone remembering to check.
 */
import fs from "node:fs";

const BASE = process.env.ORBIT_BASE ?? "http://localhost:3123";
const ONCE = process.argv.includes("--once");
const everyIdx = process.argv.indexOf("--every");
const EVERY_MS = (everyIdx > 0 ? Number(process.argv[everyIdx + 1]) : 600) * 1000;
const OUT = "docs/selfeval.md";

const pct = (n) => `${n.toFixed(1)}%`;

async function run() {
  const res = await fetch(`${BASE}/api/selfeval`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({}),
  });
  if (!res.ok) throw new Error(`${res.status} ${(await res.text()).slice(0, 200)}`);
  const { summary, failures, history } = await res.json();

  const when = new Date(summary.at).toLocaleString("en-US", { timeZone: "America/New_York" });
  console.log(`${when}  ${pct(summary.score)}  (${summary.passed}/${summary.asked})  critic ${summary.avgCritic ?? "n/a"}`);
  for (const f of failures) console.log(`   FAIL ${f.id}: ${f.q}\n        ${String(f.answer).slice(0, 110)}`);

  write(summary, failures, history);
  return summary;
}

function write(summary, failures, history) {
  const tagRow = Object.entries(summary.byTag)
    .map(([k, v]) => `| ${k} | ${v.passed}/${v.n} |`)
    .join("\n");

  const trend = (history ?? [])
    .slice(0, 12)
    .map((h) => `| ${new Date(h.at).toLocaleString("en-US", { timeZone: "America/New_York", month: "short", day: "numeric", hour: "numeric", minute: "2-digit" })} | ${pct(h.score)} | ${h.passed}/${h.asked} | ${h.avgCritic ?? "—"} |`)
    .join("\n");

  const body = `# Self-eval: can Orbit answer, and defend, what it is asked?

_Generated by \`scripts/selfeval-loop.mjs\`. Last run ${new Date(summary.at).toLocaleString("en-US", { timeZone: "America/New_York" })} ET._

**No weights change here.** Nothing in Orbit is trained or fine-tuned; see \`docs/data-and-learning.md\`. What this does is turn "can it answer questions" into a number and name exactly which ones it failed, so a change either moves that number or it did not.

## Latest run

| | |
|---|---|
| Score | **${pct(summary.score)}** (${summary.passed}/${summary.asked}) |
| Every number traced to a fact | ${summary.grounded}/${summary.asked} |
| Answers whose wording was discarded for an unsourced number | ${summary.repairedAnswers.length} |
| Out-of-scope questions it wrongly answered | ${summary.leaked.length} |
| Answers that buried the point | ${summary.buriedTheAnswer?.length ?? 0} |
| Critic average (0–5) | ${summary.avgCritic ?? "—"} |
| Median latency | ${summary.avgMs} ms |

## By kind of question

| kind | passed |
|---|---|
${tagRow}

## Trend

| run | score | passed | critic |
|---|---|---|---|
${trend}

## What each check catches

- **grounded** — every number in the answer traces to a fact it was shown. Arithmetic, not opinion. Verification is scoped to the facts the answer was built from, because checking against the whole sheet let "you have 340 usable minutes" pass on the strength of an unrelated fact that mentioned 340 XP.
- **on target** — the answer rests on the facts a right answer needs. An answer can be perfectly grounded and still be about the wrong thing.
- **led with it** — the right fact came first. Added after "will I make it to class on time?" passed while opening with two paragraphs of estimator history and reaching the bus third. An answer that buries the answer has not answered.
- **refused** — for questions Orbit genuinely cannot know (grades, exam content, weather, life advice), the only passing behaviour is saying so.

${failures.length ? `## Currently failing\n\n${failures.map((f) => `- **${f.id}** — ${f.q}\n  > ${String(f.answer).slice(0, 220)}`).join("\n")}` : "## Currently failing\n\nNothing."}
`;

  fs.mkdirSync("docs", { recursive: true });
  fs.writeFileSync(OUT, body);
}

async function tick() {
  try { await run(); } catch (e) { console.error("self-eval failed:", e.message); }
}

await tick();
if (!ONCE) {
  console.log(`\nwatching, every ${EVERY_MS / 1000}s. Ctrl-C to stop.\n`);
  setInterval(tick, EVERY_MS);
}
